2025-03-31 00:41:21,981 INFO    MainThread:21860 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-31 00:41:21,982 INFO    MainThread:21860 [wandb_setup.py:_flush():67] Configure stats pid to 21860
2025-03-31 00:41:21,982 INFO    MainThread:21860 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\.config\wandb\settings
2025-03-31 00:41:21,982 INFO    MainThread:21860 [wandb_setup.py:_flush():67] Loading settings from C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\wandb\settings
2025-03-31 00:41:21,982 INFO    MainThread:21860 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-31 00:41:21,982 INFO    MainThread:21860 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\wandb\run-20250331_004121-sveble1p\logs\debug.log
2025-03-31 00:41:21,983 INFO    MainThread:21860 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\wandb\run-20250331_004121-sveble1p\logs\debug-internal.log
2025-03-31 00:41:21,983 INFO    MainThread:21860 [wandb_init.py:init():761] calling init triggers
2025-03-31 00:41:21,983 INFO    MainThread:21860 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-31 00:41:21,983 INFO    MainThread:21860 [wandb_init.py:init():784] starting backend
2025-03-31 00:41:21,984 INFO    MainThread:21860 [wandb_init.py:init():788] sending inform_init request
2025-03-31 00:41:22,108 INFO    MainThread:21860 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-31 00:41:22,108 INFO    MainThread:21860 [wandb_init.py:init():798] backend started and connected
2025-03-31 00:41:22,111 INFO    MainThread:21860 [wandb_init.py:init():891] updated telemetry
2025-03-31 00:41:22,261 INFO    MainThread:21860 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-31 00:41:24,148 ERROR   MainThread:21860 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shrey\OneDrive\Desktop\Mtech\SEMESTER-2\DL\DL Assignment-1\venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity your_username not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-31 00:41:25,149 INFO    MsgRouterThr:21860 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
